//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubRaqueta
{
    using System;
    using System.Collections.Generic;
    
    public partial class pistas
    {
        public pistas()
        {
            this.reservas = new HashSet<reservas>();
        }
    
        public int idPista { get; set; }
        public string nombre { get; set; }
        public string ubicacion { get; set; }
        public Nullable<decimal> precioHora { get; set; }
        public byte[] foto { get; set; }
    
        public virtual ICollection<reservas> reservas { get; set; }
    }
}
